LY - press right hand button A to use EyeGaze, can generate infinite tubes now
- solved sliding issue

- this error sometimes prevent creating new tube:
UnassignedReferenceException: The variable cols2 of CollisionIgnores has not been assigned.
You probably need to assign the cols2 variable of the CollisionIgnores script in the inspector.
CollisionIgnores.DisableCollisions () (at Assets/0A_Plugins/AutoHand/Scripts/Tools/CollisionIgnores.cs:23)
CollisionIgnores.Start () (at Assets/0A_Plugins/AutoHand/Scripts/Tools/CollisionIgnores.cs:11)